import { compile } from 'json-schema-to-typescript';
import { readFile, writeFile, mkdir } from 'fs/promises';
import { dirname } from 'path';
import { DennaLoadError, DennaSchemaError } from './errors.js';

export interface CodegenOptions {
  schemas: string[];
  output?: string;
}

interface SchemaWithId {
  $id?: string;
  title?: string;
  [key: string]: unknown;
}

const HEADER = `// AUTO-GENERATED by @amatsu/denna-client — do not edit
// Run \`denna sync\` to regenerate\n\n`;

async function fetchSchema(schemaUrl: string): Promise<SchemaWithId> {
  if (schemaUrl.startsWith('https://') || schemaUrl.startsWith('http://')) {
    const response = await fetch(schemaUrl);
    if (!response.ok) {
      throw new DennaSchemaError(`Failed to fetch schema: HTTP ${response.status}`, schemaUrl);
    }
    return response.json();
  }

  try {
    const raw = await readFile(schemaUrl, 'utf-8');
    return JSON.parse(raw);
  } catch (err) {
    throw new DennaLoadError(`Failed to read schema: ${schemaUrl}`, schemaUrl, { cause: err });
  }
}

function schemaToTypeName(schema: SchemaWithId): string {
  if (schema.title) {
    return schema.title
      .split('.')
      .map((s) => s.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase()))
      .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
      .join('');
  }
  return 'UnknownSchema';
}

function isFilePath(schemaUrl: string): boolean {
  return !schemaUrl.startsWith('https://') && !schemaUrl.startsWith('http://');
}

export async function generateTypes(options: CodegenOptions): Promise<string> {
  const schemas = await Promise.all(options.schemas.map(fetchSchema));

  const typeBlocks: string[] = [];
  const schemaMapEntries: string[] = [];

  for (let i = 0; i < schemas.length; i++) {
    const schema = schemas[i];
    const schemaUrl = options.schemas[i];
    const typeName = schemaToTypeName(schema);

    const generated = await compile(schema as Record<string, unknown>, typeName, {
      bannerComment: '',
      additionalProperties: false,
      ...(isFilePath(schemaUrl) ? { cwd: dirname(schemaUrl) } : {}),
    });

    typeBlocks.push(`/* From: ${schema.$id ?? schemaUrl} */\n${generated}`);

    const rootMatch = generated.match(/export interface (\w+)/);
    if (rootMatch) {
      const id = schema.$id ?? schemaUrl;
      schemaMapEntries.push(`  "${id}": ${rootMatch[1]};`);
    }
  }

  const schemaTypeMap = schemaMapEntries.length > 0
    ? `\n// Maps schema URLs to generated types\nexport interface SchemaTypeMap {\n${schemaMapEntries.join('\n')}\n}\n`
    : '';

  const output = HEADER + typeBlocks.join('\n\n') + schemaTypeMap;

  if (options.output) {
    await mkdir(dirname(options.output), { recursive: true });
    await writeFile(options.output, output, 'utf-8');
  }

  return output;
}
